[package]
name = "DevBeh"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
libm = "0.2.8"
ndarray = "0.15.6"
plotters = "0.3.6"
# pyo3 = "0.21.2"
rand = "0.8.5"
rand_distr = "0.4.3"
rayon = "1.10.0"
statrs = "0.16.0"
weighted_rand = "0.4.2"
